server:
  port: 8080

spring:
  application:
    name: study-meetup-board
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/moit?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:changeme}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: "${JWT_SECRET:change-this-to-a-long-random-secret-in-production-please-0123456789}"
  access-token-expiration-ms: 1800000      # 30분
  refresh-token-expiration-ms: 604800000   # 7일

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
